### ISSUE TITLE
Incorrect assembly searched for static contents when building in "Release" mode

### ISSUE THREAD

**Issue by chrnola** [jugglingnutcase/Nancy.EmbeddedContent#3]
I noticed that my embedded static content wasn't being served (all of them 404'd) whenever I built my solution in the "Release" build configuration and launched my site from outside of the debugger. I enabled Nancy's request tracing functionality and eventually discovered that it was trying to find my static resources in `Nancy.dll` instead of my assembly.

Ultimately this was due to the fact that I was using `Nancy.EmbeddedContent.Conventions.StaticContentsConventionsExtensions.AddEmbeddedDirectory(this IList<Func<NancyContext, string, Response>>, string, string, params string[])` which attempts to infer the correct assembly by calling `Assembly.GetCallingAssembly()`. Unfortunately this method can behave in unexpected ways due to JIT compilation as stated by [Microsoft from their documentation](https://msdn.microsoft.com/library/system.reflection.assembly.getcallingassembly(v=vs.100).aspx):

> If the method that calls the GetCallingAssembly method is expanded inline by the just-in-time (JIT) compiler, or if its caller is expanded inline, the assembly that is returned by GetCallingAssembly may differ unexpectedly.

The workaround for me was to use the overloaded `AddEmbeddedDirectory` that takes an `Assembly` and explicitly pass in a reference to the assembly that housed my static content.

I believe that the other `AddEmbeddedDirectory` which relies on `Assembly.GetCallingAssembly()` should be deprecated.

**Comment by jugglingnutcase** [comment]
Thanks for report, I'll take a look :)

**Comment by jugglingnutcase** [comment]
Taking a look now, i see i've run into something similar to this before and i also use the overloaded method as you can see from the following (i use vb, so avert your :eyes: if you find it offensive :wink:):

```vb.net
        ' Run through embedded resources to resolve views
        '
        ' Retrieves views embedded in the current assembly
        ' We use the `ContentHelper` class to load the assembly in release mode instead of our custom root path provider
        ' because Nancy gets confused seeing our custom provider and its own and will throw an exception. Also, in addition
        ' i've hidden our custom root path provider under a debug flag because it shouldn't even be present in release mode.
        ' The embedded content provider now handles web resources in release mode.
        Dim assembly As Assembly = GetType(ContentHelper).Assembly
        If Not EmbeddedViewLocationProvider.RootNamespaces.ContainsKey(assembly) Then
            EmbeddedViewLocationProvider.RootNamespaces.Add(assembly, "Stuff.Content.Views")
        End If

        ' Add a path to each resource directory to the static conventions under the key name to simplify resource requests
        ' For ex: Nancy will look through the `Content/js` directory when the browser requests from the js url
        nancyConventions.StaticContentsConventions.AddEmbeddedDirectory("js", assembly, "Scripts")
        nancyConventions.StaticContentsConventions.AddEmbeddedDirectory("css", assembly, "css")
        nancyConventions.StaticContentsConventions.AddEmbeddedDirectory("images", assembly, "images")
```

So, i don't mind taking your advice here, but instead of deprecating i think i'll just remove the offending lines of code. i never bothered to publish this on NuGet, so a deprecation won't do much. Somebody can just clone and add that method back in if they want it.

**Comment by jugglingnutcase** [comment]
Thanks @chrnola :+1:

**Comment by chrnola** [comment]
No problem. Hopefully it'll save someone else a headache. :wink:
